### ISSUE TITLE
Bugged display / no response from program

### ISSUE THREAD

**Issue by djsime1** [TheLastMillennial/HD-Picture-Viewer#10]
In the latest compiled release, the HDPICV program just shows this weird screen. Below are two screenshots of the issue.
Screenshot from TI-Connect CE
![Screen1](https://user-images.githubusercontent.com/8518150/63824661-8c80da00-c91d-11e9-8486-2c548a5794a3.png)
Screenshot from phone
![Screen2](https://user-images.githubusercontent.com/8518150/63824662-8c80da00-c91d-11e9-8032-e2b8a298da18.jpg)
OS Version: 5.3.0.0037
If there is anything else you need, I will try to provide it.

**Comment by djsime1** [comment]
@TheLastMillennial sorry for the slow reply. When I said no response from program, I couldn't close it, even with the clear button. I had to pull out the battery and put it back in the calculator to make it work again. Thankfully vi regularly back up everything on it. Also, after converting a few images and putting them on the calculator, I still got the same result.

**Comment by TheLastMillennial** [comment]
OK, I've fixed the colors and the freezing issue, that'll be uploaded with my next commit. I'm unsure why my program isn't detecting your images. Have you tried sending over all 3 files inside the 'Example Images' folder? Have you looked at my [tutorial](https://youtu.be/s1-g8oSueQg) (specifically 6:49)? Is TI Connect CE throwing an error?

**Comment by TheLastMillennial** [comment]
Closing this issue for now, if you continue to have problems, feel free to re-open it.
