### ISSUE TITLE
Images all have the same name

### ISSUE THREAD

**Issue by TheLastMillennial** [TheLastMillennial/HD-Picture-Viewer#11]
When you have multiple images on the calculator, the first image's name is displayed on every other image. Perhaps I'm not writing to a list correctly.

**Comment by xEricL** [comment]
Still an issue. Every time I upload a new image it renames every other image to the new image's name. Tried with both version 1.0.1 and 1.0.2 (yes, I tried both HD Picture Converters too. No luck.)

**Comment by TheLastMillennial** [comment]
Resolved in the new [pre-release](https://github.com/TheLastMillennial/HD-Picture-Viewer/tree/master/Releases/Alpha%202.0.0).
