### ISSUE TITLE
ERROR INVALID 

### ISSUE THREAD

**Issue by HAKUN777** [TheLastMillennial/HD-Picture-Viewer#14]
How to solve this my calculator is TI-84 Plus CE and everytime i try to run program in my calc it shows Attempted to use a variable or function where it is not valid.

**Comment by TheLastMillennial** [comment]
Have you run the program with the Artifice jailbreak?
Jailbreak: https://yvantt.github.io/arTIfiCE/
Tutorial: https://m.youtube.com/watch?v=abB0ZEdQ1rs

**Comment by HAKUN777** [comment]
Thank you solved
