### ISSUE TITLE
RAM cleared

### ISSUE THREAD

**Issue by CodeMonkayy** [TheLastMillennial/HD-Picture-Viewer#16]
With your most recent version of HDPICV, when I try to load more than one picture, it resets my ram and this cycle repeats everytime I open the program. Is this because it is in Beta still or am I doing something wrong, installed all libraries as needed including Cesium and have OS 5.3.1

Sorry for any trouble and Thank you for this amazing app

The sample images by itself works fine, as soon as I use a converted image, it resets Ram

**Comment by TheLastMillennial** [comment]
I cannot reproduce with images I've tried. Did you previously put pictures on the calculator that were made with an older version of the converter? Those would not be compatible with this beta since compression is now used.

**Comment by TheLastMillennial** [comment]
No response in months. Re-open if necessary.
