### ISSUE TITLE
when using converter there is an issue

### ISSUE THREAD

**Issue by Agenthalal** [TheLastMillennial/HD-Picture-Viewer#20]
![Screenshot 2023-12-17 103118](https://github.com/TheLastMillennial/HD-Picture-Viewer/assets/154074532/f6e8f207-5c44-46cc-84ee-38105a59f2f2)
I dont know what causing this issue

**Comment by TheLastMillennial** [comment]
The error says the image is being used by another process. Unfortunately windows does not have a built-in way to see what processes is currently using it.

You can either restart your computer or install Microsoft Powertoys which has a tool to see what process is using the image.
