### ISSUE TITLE
Splitting images in half

### ISSUE THREAD

**Issue by dreamlightsgroup** [TheLastMillennial/HD-Picture-Viewer#5]
Hey so I'm getting the program to work with your example images but not with my own. I'm very much confused on how to split in half and convert, can you please create a quick video tutorial on that?
Thanks!

**Comment by arbazkhan334** [comment]
> I think there's a tool included that does that for you.

I can convert the image but I don't know what he means by splitting in half. You mean I should find a tool online that does that for me and then convert the two images?

**Comment by arbazkhan334** [comment]
Ok so I used this website to make two halves of the picture https://pinetools.com/split-image
but when I put it in my calculator I don't see my picture there
