### ISSUE TITLE
Image broken when converted with HDpic Converter

### ISSUE THREAD

**Issue by arbazkhan334** [TheLastMillennial/HD-Picture-Viewer#6]
Hi, so I finally got to convert the image with the HDpic converter and the image showed up in my calculator. But now the image is so distorted. All I see is colorful pixels. Can this issue be fixed? 

I posted an image of it on my google drive you can take a look at what I mean here https://drive.google.com/file/d/1IkuXQ_gqDclltvlKyGjHTO5K5QFJOsl1/view?usp=sharing

**Comment by ndrew222** [comment]
I'm experiencing the same issue. 
I've also tried using the HD Picture Converter CE.exe from the master/HD-Picture-Viewer/HDpicConverter and it ends up corrupted, though basic shapes are visible from the image

**Comment by TheLastMillennial** [comment]
Oh dear, I missed this issue for so long it became obsolete. I'm so sorry about this! Try the new beta, it contains a proper converter and video tutorial.
